
.PHONY: all clean

all: gopngquant.exe

clean:
	rm ./gopngquant.exe || true
	
gopngquant.exe: main.go
	( source ~/.cygwin-toolchain-switcher/use-toolchain-x86_64-w64-mingw32.sh && go build -a -ldflags '-s -w' )
